### PR TITLE
Adding basic support for the Tinkergraph in-memory graph database engine

### PR DESCRIPTION
**Pull request by davebshow**
This PR adds support for Tinkergraph, an in-memory reference implementation of a Tinkerpop3 enabled graph database system. This IS NOT meant to be a standalone backend for SylvaDB, instead it is a building block towards adding support for the new Titan when released, and will facilitate the use of any graphdb that uses the Gremlin Server for communication.

For connectivity it uses `gremlinrestclient`, a simple client based on `requests`. This client is pretty alpha, but it has a fairly comprehensive test suite. 

This PR makes almost no changes to the existing code base. It adds a `tinkergraph.GraphDatabase` and `tinkergraph.Q` class to the existing implementations. These classes will be inherited from (and inevitably refactored) when adding support for Titan.

A few things to note:

 - Graph data is not persisted. Once the Server is stopped all node and edge data is lost.

 - Due to the lack of text searching capabilities, the Tinkergraph backend is not fully functional. For example, relationship creation must have exact text matches to work.

 - Because of this lack of functionality. The Tinkergraph backend is not run against the SylvaDB test suite, and does not work with `reports`, `queries`, and `analytics` (no dump implmented).

 - `tinkergraph.GraphDatabase` currently inherits from `blueprints.GraphDatabase` and therefore relies on the old `pyblueprints` API. In the future this will be upgraded to a more modern, lower level API.

In the near future, I plan to submit pull requests adding support for Titan, and Titan with Hadoop/Spark/Giraph graph analytics enabled. The Titan backend will eventually support all current SylvaDB apps. 

Thanks @versae de antemano!

### CODE REVIEW

**Comment by versae** [comment]
This is awesome! Promising first steps :dancer: I was thinking that the best way might be by creating a new remote branch `tinkergraph`, so when all the work is done we can safely merge. WDYT?

**Comment by davebshow** [comment]
SGTM. Thanks Javi, I'm pretty stoked on the project. Titan is looking like it's gonna be pretty sweet :fire:

**Comment by davebshow** [comment]
Will I need to submit a new PR to the new target branch then?

**Comment by versae** [comment]
I could manually merge to the branch, but it's possibly easier if you could just cancel this PR and do it again on the new branch.

**Comment by davebshow** [comment]
Will do. Maybe we should call the branch `tp3` or `tinkerpop`, and we can merge when we get tested Titan support, or just create a special docker for the Titan installation...

**Comment by versae** [comment]
Alright. [Branch created](https://github.com/CulturePlex/Sylva/tree/tinkerpop) :+1:

**Pull request closed without merging**
